# Generated by Django 4.2 on 2025-02-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
